CREATE TABLE IF NOT EXISTS tb_list (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id UUID REFERENCES tb_user(id)
);